version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phoenix_ecto
    versions:
    - "> 3.5.0"
  - dependency-name: ecto_sql
    versions:
    - 3.6.0
  - dependency-name: timex
    versions:
    - 3.6.4
    - 3.7.1
    - 3.7.3
  - dependency-name: sentry
    versions:
    - 8.0.4
